name: Build Image

on:
  push:
    paths:   # 这里是用来指定哪个文件更改，才会触发的
      - './ci/version.txt'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Source Build Env
        id: source-build-env
        run: |
          cat ./ci/build.env >> $GITHUB_ENV
          echo "VERSION=$(cat ./ci/version.txt)" >> $GITHUB_ENV
          echo "APPS_JSON_BASE64=$(base64 -w 0 ./ci/apps.json)" >> $GITHUB_ENV

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - uses: int128/kaniko-action@v1
        with:
          push: true
          cache: true
          kaniko-args: |
            --build-arg=PYTHON_VERSION=${{ inputs.py-version || env.PY_VERSION }}
            --build-arg=NODE_VERSION=${{ inputs.nodejs-version || env.NODEJS_VERSION }}
            --build-arg=APPS_JSON_BASE64=${{ inputs.apps-json-base64 || env.APPS_JSON_BASE64 }}
            --context=${{ inputs.context || env.CONTEXT }}
            --destination=${{ secrets.DOCKER_USERNAME }}/${{ inputs.image || env.IMAGE }}:${{ inputs.version || env.VERSION }}
            --destination=${{ secrets.DOCKER_USERNAME }}/${{ inputs.image || env.IMAGE }}:latest
          file: ${{ inputs.dockerfile || env.DOCKERFILE }}
